---
# This playbook includes all the steps to deploy our web app
# it uses the following modules in this order:

# - pull node-js version 14.x files
# - update cache and install node js
# - clone the git repository of the app
# - install dotenv in the repository directory

# *only for production enviroment*
# - create .env file with the given variables for production env
# - initate db via one of the production servers

# *only for staging enviroment*
# - create .env file with the given variables for staging env
# - initiate the db via one of the staging servers

# *back to all enviroments*
# - create a cron job that deployes the app on server restart
# - deploy the app
#

- hosts: all
  become: true
  tasks:


  - name: install zip
    apt:
      update_cache: yes
      name: zip
      state: present
  
  - name: unzip package
    ansible.builtin.unarchive:
      src: /home/adminuser/myagent/_work/r1/a/_OriTzadok-hub.bootcamp-app/weight-artifact/a/webapp.zip
      dest: /home/adminuser/

  
  - name: pull nodejs 14.x.x
    shell: curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -
    args:
      warn: no

  - name: install nodejs 14.x.x
    become: yes
    apt:
      update_cache: yes
      name: nodejs
      state: present

  - name: Install dotenv
    become: yes
    npm:
      path: /home/adminuser/s
      name: dotenv
      state: latest

  - name: Create .env
    copy:
      dest: "/home/adminuser/s/.env"
      content: |
        PORT=8080
        HOST=0.0.0.0
         
        PGHOST={{ pg_host }}
        PGUSERNAME={{ pg_user }}
        PGDATABASE={{ pg_name }}
        PGPASSWORD={{ pg_password }}
        PGPORT=5432
        HOST_URL={{ host_url }}
        COOKIE_ENCRYPT_PWD={{ cookie_pwd }}
        NODE_ENV=development
        OKTA_ORG_URL={{ okta_url }}
        OKTA_CLIENT_ID={{ okta_client_id }}
        OKTA_CLIENT_SECRET={{ okta_client_secret }}
  
  - name: init db
    shell: chdir=/home/adminuser/s/ npm run initdb
    run_once: true
  

  - name: deploy the app after restart
    cron:
      name: "launch after reboot"
      special_time: reboot
      job: cd /home/adminuser/s/ && npm run dev
  
  - name: deploy app
    shell: chdir=/home/adminuser/s/ npm run dev
    async: 30000000
    poll: 0
