---

- hosts: all
  become: true
  tasks:
  
  - name: pull nodejs 14.x.x
    shell: curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -
    args:
      warn: no

  - name: install nodejs 14.x.x
    become: yes
    apt:
      update_cache: yes
      name: nodejs
      state: present

  - name: Git checkout
    ansible.builtin.git:
      repo: 'https://github.com/OriTzadok-hub/bootcamp-app.git'
      dest: /path/to/repo/locally
      update: no

  - name: Install dotenv
    become: yes
    npm:
      path: /path/to/repo/locally
      name: dotenv
      state: latest

  
- hosts: production
  become: true
  tasks:

  - name: Create .env
    copy:
      dest: "/path/to/repo/locally/.env"
      content: |
        PORT=8080
        HOST=0.0.0.0
         
        PGHOST={{ pg_host }}
        PGUSERNAME={{ pg_user }}
        PGDATABASE={{ pg_name }}
        PGPASSWORD={{ pg_password }}
        PGPORT=5432

        HOST_URL={{ host_url }}
        COOKIE_ENCRYPT_PWD={{ cookie_pwd }}
        NODE_ENV=development

        OKTA_ORG_URL={{ okta_url }}
        OKTA_CLIENT_ID={{ okta_client_id }}
        OKTA_CLIENT_SECRET={{ okta_client_secret }}

- hosts: test
  become: true
  tasks:

  - name: Create .env
    copy:
      dest: "/path/to/repo/locally/.env"
      content: |
        PORT=8080
        HOST=localhost

        PGHOST=10.0.2.4
        PGUSERNAME=
        PGDATABASE=
        PGPASSWORD=
        PGPORT=5432

        HOST_URL=
        COOKIE_ENCRYPT_PWD=
        NODE_ENV=development

        OKTA_ORG_URL=
        OKTA_CLIENT_ID=
        OKTA_CLIENT_SECRET=

- hosts: all
  become: true
  tasks:

  - name: init db
    shell: chdir=/path/to/repo/locally/ npm run initdb
    run_once: true

  - name: deploy the app after restart
    cron:
      name: "launch after reboot"
      special_time: reboot
      job: cd /path/to/repo/locally/ && npm run dev

  - name: deploy app
    shell: chdir=/path/to/repo/locally/ npm run dev
    async: 30
    poll: 0
